DjangoDemo/blog/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import * #PostViewSet, TestCaseViewSet, TagViewSet, showLog, executeSuite, getFileTreeList, saveSuiteFile
app_name = 'blog'
router = DefaultRouter()
#router.register(r'show_books', PostViewSet)
router.register(r'show_testcases', TestCaseViewSet, basename='tc')
router.register(r'show_tags', TagViewSet)
urlpatterns = [
    #path('', views.index, name='index'),
    #path('show_books', views.getAllBooks, name='showBooks')
    path(r'api/', include(router.urls)),
    path(r'api/show_log/', showLog, name='test'),
    path(r'api/execute_suite/', executeSuite, name='execute'),
    path(r'api/getFileTreeList/', getFileTreeList, name='getFileTreeList'),
    path(r'api/getFileContent/', getFileContent, name='getFileContent'),
    path(r'api/saveSuiteFile/', saveSuiteFile, name='saveSuiteFile'),
    path(r'api/saveRawFile/', saveRawFile, name='saveRawFile')
]

DjangoDemo/newblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from rest_framework.routers import DefaultRouter

from newblog.views import AuthorView, SearchView, IndexView, CategoryView, TagView, PostListView, PostDetailView, post_list, post_detail
from config.views import LinkListView
from config.views import links
from comment.views import CommentView
#from blogproject.custom_site import custom_site


app_name = 'newblog'

urlpatterns = [
    #url(r'^$', post_list),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    #url(r'^post/(?P<post_id>\d+).html$', post_detail, name='post-detail'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^author/(?P<author_id>\d+)/$', AuthorView.as_view(), name='author'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),

]

DjangoDemo/newblog/models.py
import mistune

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from . import logger

class Category(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),

    )

    name = models.CharField(max_length=50, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    is_nav = models.BooleanField(default=False, verbose_name='是否为导航')
    author = models.ForeignKey(User, on_delete=None, verbose_name='作者')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '分类'

    def __str__(self):
        return self.name



    @classmethod
    def get_navs(cls):
        nav_categories = []
        non_nav_categories = []
        categories = cls.objects.filter(status=cls.STATUS_NORMAL)
        for category in categories:
            if category.is_nav:
                nav_categories.append(category)
            else:
                non_nav_categories.append(category)
        return {
            'navs': nav_categories,
            'categories': non_nav_categories,
        }



class Tag(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),

    )

    name = models.CharField(max_length=10, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    is_nav = models.BooleanField(default=False, verbose_name='是否为导航')
    author = models.ForeignKey(User, on_delete=None, verbose_name='作者')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '标签'

    def __str__(self):
        return self.name


class Post(models.Model):
    list_show_num = 5
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_DRAFT = 2
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
        (STATUS_DRAFT, '草稿'),

    )

    title = models.CharField(max_length=255, verbose_name='标题')
    desc = models.CharField(max_length=1024, blank=True, verbose_name='摘要')
    content = models.TextField(verbose_name='正文', help_text='正文必须为MarkDown格式')
    content_html = models.TextField(verbose_name='正文html代码', blank=True, editable=False)
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    category = models.ForeignKey(Category, on_delete=None, verbose_name='分类')
    tag = models.ManyToManyField(Tag, verbose_name='标签')
    is_nav = models.BooleanField(default=False, verbose_name='是否为导航')
    author = models.ForeignKey(User, on_delete=None, verbose_name='作者')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    pv = models.PositiveIntegerField(default=1)
    uv = models.PositiveIntegerField(default=1)
    is_md = models.BooleanField(default=False, verbose_name="markdown语法")

    def save(self, *args, **kwargs):
        if self.is_md:
            self.content_html = mistune.markdown(self.content)
        else:
            self.content_html = self.content
        super().save(*args, **kwargs)

    @classmethod
    def hot_posts(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-pv')[0:cls.list_show_num]

    def get_all_tag(self):
        return self.tag.all()

    @staticmethod
    def get_by_tag(tag_id):
        try:
            tag = Tag.objects.get(id=tag_id)
        except Tag.DoesNotExist:
            tag = None
            post_list = []
        else:
            post_list = tag.post_set.filter(status = Post.STATUS_NORMAL).select_related('author')
        return post_list, tag

    @staticmethod
    def get_by_category(category_id):
        try:
            category = Category.objects.get(id=category_id)
        except Category.DoesNotExist:
            category = None
            post_list = []
        else:
            post_list = category.post_set.filter(status = Post.STATUS_NORMAL).select_related('author', 'category')
        return post_list, category

    @classmethod
    def latest_posts(cls, with_related=True):
        queryset = cls.objects.filter(status=cls.STATUS_NORMAL)
        if with_related:
            queryset = queryset.select_related('author', 'category')
        return queryset

    class Meta:
        verbose_name = verbose_name_plural = '文章'
        ordering = ['-id']

    def __str__(self):
        return self.title

DjangoDemo/newblog/views.py
from datetime import date

from django.core.cache import cache
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import DetailView
from django.views.generic import ListView
from django.db.models import Q, F

from django.contrib.auth.models import User

from . import logger
from .models import Post, Category, Tag
from config.models import SideBar
# Create your views here.


class CommonViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'sidebars': SideBar.get_all(),
        })
        context.update(Category.get_navs())
        return context


class IndexView(CommonViewMixin, ListView):
    logger.info("enter into f indexview")
    queryset = Post.latest_posts()
    logger.info(queryset[0].get_all_tag())
    paginate_by = 5
    context_object_name = 'post_list'
    template_name = 'newblog/list.html'
    logger.info("out of indexview")


class AuthorView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        author_id = self.kwargs.get('author_id')
        user_obj = get_object_or_404(User, pk=author_id)
        context.update({
            'author': user_obj,
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        author_id = self.kwargs.get("author_id")
        return queryset.filter(author_id=author_id)


class SearchView(IndexView):
    def get_context_data(self):
        context = super().get_context_data()
        context.update({
            'keyword': self.request.GET.get('keyword', '')
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword')
        if not keyword:
            return queryset
        return queryset.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword))


class CategoryView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(Category, pk=category_id)
        context.update({
            'category': category,
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id)


class TagView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_id = self.kwargs.get('tag_id')
        tag = get_object_or_404(Tag, pk=tag_id)
        context.update({
            'tag': tag,
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_id = self.kwargs.get('tag_id')
        return queryset.filter(tag=tag_id)


class PostListView(ListView):
    queryset = Post.latest_posts()
    paginate_by = 10
    context_object_name = 'post_list'
    template_name = 'newblog/list.html'


class PostDetailView(CommonViewMixin, DetailView):
    queryset = Post.latest_posts()
    template_name = 'newblog/detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

    def handle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = 'pv:%s:%s' % (uid, self.request.path)
        uv_key = 'uv:%s:%s:%s' % (uid, str(date.today()), self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key, 1, 1*60)

        if not cache.get(uv_key):
            increase_uv = True
            cache.set(uv_key, 1, 24*60*60)

        if increase_pv and increase_uv:
            Post.objects.filter(pk=self.object.id).update(pv=F('pv') + 1, uv=F('uv') + 1)
        elif increase_pv:
            Post.objects.filter(pk=self.object.id).update(pv=F('pv')+1)
        elif increase_uv:
            Post.objects.filter(pk=self.object.id).update(uv=F('uv')+1)


def post_list(request, category_id=None, tag_id=None):
    logger.info("Enter into function post_list")
    tag = None
    category = None
    if tag_id:
        post_list, tag = Post.get_by_tag(tag_id)
    elif category_id:
        logger.info('category class')
        post_list, category = Post.get_by_category(category_id)
        logger.info(post_list)
    else:
        post_list = Post.latest_posts()


    context = {
        'category': category,
        'tag': tag,
        'post_list': post_list,
        'sidebars': SideBar.get_all(),
    }
    context.update(Category.get_navs())
    return render(request, 'newblog/list.html', context=context)#{'post_list': post_list})

def post_detail(request, post_id):
    try:
        logger.info('in post detail')
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        post = None

    context = {
        'post': post,
        'sidebars': SideBar.get_all()
    }
    context.update(Category.get_navs())
    logger.info(context)
    return render(request, 'newblog/detail.html', context=context)

DjangoDemo/themes/bootstrap/templates/newblog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %}- newblog 博客系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.css">
    <style>
    .post {
        margin-bottom: 5px;
    }
    </style>
</head>
<body>
    <div class="container head">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/newblog/">首页</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                {% for cate in navs %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'newblog:category-list' cate.id %}">{{ cate.name }}</a>
                    </li>
                {% endfor %}
                </ul>
                <form class="form-inline" action='/newblog/search/' method='GET'>
                    <input class="from-control" type="search" name="keyword" placeholder="Search" aria-label="Search" value="{{ keyword }}">
                    <button class="btn btn-outline-success" type="submit">搜索</button>
                </form>
            </div>
        </nav>
        <div class="jumbotron">
            <h1 class="display-4">NewBlog</h1>
            <p class="lead">基于Django的多人博客系统 </p>
        </div>
    </div>
    <div class="container main">
        <div class="row">
            <div class="col-9 post-list">
                {% block main %}
                {% endblock %}
            </div>
            <div class="col-3">
                {% block sidebar %}
                    {% for sidebar in sidebars %}
                    <div class="card sidebar">
                        <div class="card-body">
                            <h4 class="card-title">*** {{ sidebar.title }} *** </h4>
                            <p>{{ sidebar.content_html}}</p>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="card sidebar">
                        <div class="card-body">
                            <span class="card-title"><a href="{% url 'newblog:links' %}">*** 友情链接 ***</a></span>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
    <footer class="footer">
        {% block footer %}
        <div class="container">
            <hr/>
            <nav class="nav category">
                {% for cate in navs %}
                <a href="{% url 'newblog:category-list' cate.id %}" class="nav-link">{{ cate.name }}</a>
                {% endfor %}
            </nav>
        </div>
        <div class="container power">
            <span class="text-muted">Power By newbolgowner</span>
        </div>
        {% endblock %}
    </footer>
</body>
</html>

DjangoDemo/themes/bootstrap/templates/newblog/detail.html
{% extends "./base.html" %}
{% load comment_block %}

{% block title %}
    {% if tag %}
    标签页: {{ tag.name }}
    {% elif category %}
    分类页：{{ category.name }}
    {% endif %}
{% endblock %}

{% block main %}
    {% if post %}
    <h1>{{ post.title }}</h1>
    <div>
        <span class="card-link">创建时间: {{ post.created_time }} </span>
        <span class="card-link">分类:<a href="{% url 'newblog:category-list' post.category.id %}"> {{ post.category.name }}</a></span>
        <span class="card-link">作者: {{ post.author.username }}</span>
        <span class="card-link">标签: 
            {% for tag in post.tag.all %}
            <a href="{% url 'newblog:tag-list' tag.id %}">{{ tag.name }}</a>
            {% endfor %}
        </span>
    </div>
    <hr/>
    <p>
    {% autoescape off %}
    {{ post.content_html }}
    {% endautoescape %}
    </p>
    {% endif %}
    {% comment_block request.path %}
{% endblock %}

DjangoDemo/themes/bootstrap/templates/newblog/list.html
{% extends "./base.html" %}
{% block title %}
    {% if tag %}
    标签页: {{ tag.name }}
    {% elif category %}
    分类页：{{ category.name }}
    {% elif author%}
    作者：{{ author.username}}
    {% else %}
    首页
    {% endif %}
{% endblock %}

{% block main %}
    {% for post in post_list %}
    <div class="card post">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'newblog:post-detail' post.id %}">{{ post.title }}</a></h5>
            <span class="card-link">作者：<a href="{% url 'newblog:author' post.author.id %}"> {{ post.author.username }} </a></span>
            <span class="card-link">分类：<a href="{% url 'newblog:category-list' post.category.id %}"> {{ post.category.name }}</a></span>
            <span class="card-link">标签: 
            {% for tag in post.tag.all %}
            <a href="{% url 'newblog:tag-list' tag.id %}">{{ tag.name }}</a>
            {% endfor %}
            </span>
            <p class="card text">{{ post.desc }}<a href="{% url 'newblog:post-detail' post.id %}">完整内容</a> </p>
        </div>
    </div>
    {% endfor %}
    {% if page_obj %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    {% endif %}
{% endblock %}